In [ ]:
# Q1 DISSIMILARITY FOR ASYMMETRIC ATTRIBUTE
import numpy as np

data = [[1, 0, 1, 0, 0, 0], [1, 1, 0, 0, 0, 0], [1, 0, 1, 0, 1, 0]]
score = []

def matrix(L1, L2):
    ans_mat = np.zeros((2, 2))
    for i in range(6):
        if L1[i] == 1 and L2[i] == 1:
            ans_mat[0, 0] += 1
        elif L1[i] == 1 and L2[i] == 0:
            ans_mat[0, 1] += 1
        elif L1[i] == 0 and L2[i] == 1:
            ans_mat[1, 0] += 1
        else:
            ans_mat[1, 1] += 1
    return ans_mat

for i in range(len(data)):
    for j in range(i + 1, len(data)):
        ans_mat = matrix(data[i], data[j])
        print(f"Matrix for data[{i}] and data[{j}]:\n{ans_mat}")
        denom = ans_mat[1,0] + ans_mat[0,1] + ans_mat[0,0]
        if denom == 0:
            cal = 0
        else:
            cal = (ans_mat[1,0] + ans_mat[0,1]) / denom
        print(f"Dissimilarity score for data[{i}] and data[{j}]: {cal}")
        score.append((i, j, cal))

sorted_scores = sorted(score, key=lambda x: x[2], reverse=True)
print("Sorted dissimilarity scores (with pairs): ", sorted_scores)

highest_dissimilarity_pair = sorted_scores[0]
print(f"Pair with highest dissimilarity: data[{highest_dissimilarity_pair[0]}] and data[{highest_dissimilarity_pair[1]}] with a dissimilarity score of {highest_dissimilarity_pair[2]}")

print("All dissimilarity scores (sorted): ", [x[2] for x in sorted_scores])



# Q2 DISSIMILARITY FOR NUMINAL ATTRIBUTE
import numpy as np

data = [
    [1, 'code A'],
    [2, 'code B'],
    [3, 'code C'],
    [4, 'code A']
]

object_ids = [row[0] for row in data]
attributes = [row[1] for row in data]
score = []

def matrix(attr1, attr2):
    ans_mat = np.zeros((2, 2))
    if attr1 == attr2:
        ans_mat[0, 0] += 1
    else:
        ans_mat[1, 0] += 1
    return ans_mat

for i in range(len(attributes)):
    for j in range(i + 1, len(attributes)):
        ans_mat = matrix(attributes[i], attributes[j])
        print(f"Matrix for object_id[{i}] and object_id[{j}]:\n{ans_mat}")
        denom = ans_mat[1,0] + ans_mat[0,0]
        if denom == 0:
            cal = 0
        else:
            cal = ans_mat[1,0] / denom
        print(f"Dissimilarity score for object_id[{i}] and object_id[{j}]: {cal}")
        score.append((object_ids[i], object_ids[j], cal))

sorted_scores = sorted(score, key=lambda x: x[2], reverse=True)
print("Sorted dissimilarity scores (with pairs): ", sorted_scores)

highest_dissimilarity_pair = sorted_scores[0]
print(f"Pair with highest dissimilarity: object_id[{highest_dissimilarity_pair[0]}] and object_id[{highest_dissimilarity_pair[1]}] with a dissimilarity score of {highest_dissimilarity_pair[2]}")

print("All dissimilarity scores (sorted): ", [x[2] for x in sorted_scores])



# Q3 DISSIMILARITY FOR MIXED TYPE OF ATTRIBUTE
import numpy as np

data = [
    [1, 'code A', 'excellent', 45],
    [2, 'code B', 'fair', 22],
    [3, 'code C', 'good', 64],
    [4, 'code D', 'excellent', 28]
]

object_ids = [row[0] for row in data]
nominal_attributes = [row[1] for row in data]
ordinal_attributes = [row[2] for row in data]
numeric_attributes = [row[3] for row in data]

ordinal_mapping = {'fair': 1, 'good': 2, 'excellent': 3}
ordinal_encoded = [ordinal_mapping[attr] for attr in ordinal_attributes]

score = []

def nominal_dissimilarity(attr1, attr2):
    return 0 if attr1 == attr2 else 1

def ordinal_dissimilarity(attr1, attr2):
    return abs(attr1 - attr2) / (max(ordinal_mapping.values()) - min(ordinal_mapping.values()))

def numeric_dissimilarity(attr1, attr2):
    return abs(attr1 - attr2) / (max(numeric_attributes) - min(numeric_attributes))

for i in range(len(data)):
    for j in range(i + 1, len(data)):
        nom_diss = nominal_dissimilarity(nominal_attributes[i], nominal_attributes[j])
        ord_diss = ordinal_dissimilarity(ordinal_encoded[i], ordinal_encoded[j])
        num_diss = numeric_dissimilarity(numeric_attributes[i], numeric_attributes[j])

        combined_diss = (nom_diss + ord_diss + num_diss) / 3
        
        score.append((object_ids[i], object_ids[j], combined_diss))

sorted_scores = sorted(score, key=lambda x: x[2], reverse=True)
print("Sorted dissimilarity scores (with pairs): ", sorted_scores)

highest_dissimilarity_pair = sorted_scores[0]
print(f"Pair with highest dissimilarity: object_id[{highest_dissimilarity_pair[0]}] and object_id[{highest_dissimilarity_pair[1]}] with a dissimilarity score of {highest_dissimilarity_pair[2]}")

print("All dissimilarity scores (sorted): ", [x[2] for x in sorted_scores])



# DISSIMILARITY FOR NUMERIC ATTRIBUTE
import numpy as np

data = [
    [1, 45],
    [2, 22],
    [3, 64],
    [4, 28]
]

object_ids = [row[0] for row in data]
numeric_attributes = [row[1] for row in data]
score = []

def numeric_dissimilarity(val1, val2):
    return abs(val1 - val2) / (max(numeric_attributes) - min(numeric_attributes))

for i in range(len(data)):
    for j in range(i + 1, len(data)):
        diss = numeric_dissimilarity(numeric_attributes[i], numeric_attributes[j])
        print(f"Dissimilarity score for object_id[{object_ids[i]}] and object_id[{object_ids[j]}]: {diss}")
        score.append((object_ids[i], object_ids[j], diss))

sorted_scores = sorted(score, key=lambda x: x[2], reverse=True)
print("Sorted dissimilarity scores (with pairs): ", sorted_scores)

highest_dissimilarity_pair = sorted_scores[0]
print(f"Pair with highest dissimilarity: object_id[{highest_dissimilarity_pair[0]}] and object_id[{highest_dissimilarity_pair[1]}] with a dissimilarity score of {highest_dissimilarity_pair[2]}")

print("All dissimilarity scores (sorted): ", [x[2] for x in sorted_scores])


# ORDINAL ATTRIBUTE
import numpy as np

# Define ordinal data with weights
ordinal_data = [
    [1, 3], 
    [2, 2],
    [3, 1], 
    [4, 3] 
]

# Mapping ordinal attributes to numerical values
ordinal_mapping = {"excellent": 3, "good": 2, "fair": 1}

# Convert ordinal attributes to numerical values
numerical_data = []
for row in ordinal_data:
    numerical_row = [row[0], ordinal_mapping.get(row[1], 0)]
    numerical_data.append(numerical_row)

score = []

def matrix(L1, L2):
    ans_mat = np.zeros((2, 2))
    for i in range(len(L1)):
        if L1[i] == L2[i]:
            ans_mat[0, 0] += 1
        elif L1[i] != L2[i]:
            ans_mat[0, 1] += 1
    return ans_mat

for i in range(len(numerical_data)):
    for j in range(i + 1, len(numerical_data)):
        ans_mat = matrix(numerical_data[i], numerical_data[j])
        print(f"Matrix for numerical_data[{i}] and numerical_data[{j}]:\n{ans_mat}")
        denom = ans_mat[0, 1] + ans_mat[0, 0]
        if denom == 0:
            cal = 0
        else:
            cal = ans_mat[0, 1] / denom
        print(f"Dissimilarity score for numerical_data[{i}] and numerical_data[{j}]: {cal}")
        score.append((i, j, cal))

sorted_scores = sorted(score, key=lambda x: x[2], reverse=True)
print("Sorted dissimilarity scores (with pairs): ", sorted_scores)

highest_dissimilarity_pair = sorted_scores[0]
print(f"Pair with highest dissimilarity: numerical_data[{highest_dissimilarity_pair[0]}] and numerical_data[{highest_dissimilarity_pair[1]}] with a dissimilarity score of {highest_dissimilarity_pair[2]}")

print("All dissimilarity scores (sorted): ", [x[2] for x in sorted_scores])



# SYMMETRIC ATTRIBUTE
import numpy as np

data = [[1, 0, 1, 0, 0, 0], [1, 1, 0, 0, 0, 0], [1, 0, 1, 0, 1, 0]]
score = []

def matrix(L1, L2):
    ans_mat = np.zeros((2, 2))
    for i in range(6):
        if L1[i] == 1 and L2[i] == 1:
            ans_mat[0, 0] += 1
        elif L1[i] == 1 and L2[i] == 0:
            ans_mat[0, 1] += 1
        elif L1[i] == 0 and L2[i] == 1:
            ans_mat[1, 0] += 1
        else:
            ans_mat[1, 1] += 1
    return ans_mat

for i in range(len(data)):
    for j in range(i + 1, len(data)):
        ans_mat = matrix(data[i], data[j])
        print(f"Matrix for data[{i}] and data[{j}]:\n{ans_mat}")
        denom = ans_mat[1,0] + ans_mat[0,1] + ans_mat[0,0]
        if denom == 0:
            cal = 0
        else:
            cal = (ans_mat[1,0] + ans_mat[0,1]) / denom
        print(f"Dissimilarity score for data[{i}] and data[{j}]: {cal}")
        score.append((i, j, cal))

sorted_scores = sorted(score, key=lambda x: x[2], reverse=True)
print("Sorted dissimilarity scores (with pairs): ", sorted_scores)

highest_dissimilarity_pair = sorted_scores[0]
print(f"Pair with highest dissimilarity: data[{highest_dissimilarity_pair[0]}] and data[{highest_dissimilarity_pair[1]}] with a dissimilarity score of {highest_dissimilarity_pair[2]}")

print("All dissimilarity scores (sorted): ", [x[2] for x in sorted_scores])



# COSINE SIMILARITY
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

# Define the data
data = [
    [5, 0, 3, 0, 2, 0, 0, 2, 0, 0], 
    [3, 0, 2, 0, 1, 1, 0, 1, 0, 1], 
    [0, 7, 0, 2, 1, 0, 0, 3, 0, 0], 
    [0, 1, 0, 0, 1, 2, 2, 0, 3, 0]  
]

data = np.array(data)
cosine_sim = cosine_similarity(data)

# Displaying cosine similarities
print("Cosine Similarity Matrix:")
print(cosine_sim)

# Get the indices of pairs with the highest cosine similarity
sorted_sim_indices = np.argsort(-cosine_sim, axis=None)
pairs_with_scores = [(i // cosine_sim.shape[1], i % cosine_sim.shape[1], cosine_sim.flatten()[i]) for i in sorted_sim_indices]

# Filter out the pairs where i == j (same row comparison)
filtered_pairs_with_scores = [pair for pair in pairs_with_scores if pair[0] != pair[1]]

print("\nPairs with highest cosine similarity (excluding self-comparison):")
for i, (row1, row2, score) in enumerate(filtered_pairs_with_scores[:10]): # Display top 10 pairs
    print(f"Pair {i + 1}: Row {row1} and Row {row2} with cosine similarity {score:.4f}")

# Find the pair with the highest cosine similarity
highest_cos_sim_pair = filtered_pairs_with_scores[0]
print(f"\nPair with highest cosine similarity: Row {highest_cos_sim_pair[0]} and Row {highest_cos_sim_pair[1]} with cosine similarity {highest_cos_sim_pair[2]:.4f}")

# Display all cosine similarity scores sorted (excluding self-comparison)
cos_sim_scores = [score for _, _, score in filtered_pairs_with_scores]
print("\nAll cosine similarity scores (sorted):")
print(cos_sim_scores)

Matrix for data[0] and data[1]:
[[1. 1.]
 [1. 3.]]
Dissimilarity score for data[0] and data[1]: 0.6666666666666666
Matrix for data[0] and data[2]:
[[2. 0.]
 [1. 3.]]
Dissimilarity score for data[0] and data[2]: 0.3333333333333333
Matrix for data[1] and data[2]:
[[1. 1.]
 [2. 2.]]
Dissimilarity score for data[1] and data[2]: 0.75
Sorted dissimilarity scores (with pairs):  [(1, 2, np.float64(0.75)), (0, 1, np.float64(0.6666666666666666)), (0, 2, np.float64(0.3333333333333333))]
Pair with highest dissimilarity: data[1] and data[2] with a dissimilarity score of 0.75
All dissimilarity scores (sorted):  [np.float64(0.75), np.float64(0.6666666666666666), np.float64(0.3333333333333333)]
Matrix for object_id[0] and object_id[1]:
[[0. 0.]
 [1. 0.]]
Dissimilarity score for object_id[0] and object_id[1]: 1.0
Matrix for object_id[0] and object_id[2]:
[[0. 0.]
 [1. 0.]]
Dissimilarity score for object_id[0] and object_id[2]: 1.0
Matrix for object_id[0] and object_id[3]:
[[1. 0.]
 [0. 0.]]
Dissimilari